### PR TITLE
Hide green block when user_name and host_name are disabled

### PR DESCRIPTION
**Pull request by mdluo**
If both POWERLINE_HIDE_USER_NAME and POWERLINE_HIDE_HOST_NAME are set
to “false”, hide the blank green block.

### CODE REVIEW

**Comment by mdluo** [comment]
qq20150408-1 2x

**Comment by jeremyFreeAgent** [comment]
Hi @mdluo! Thanky for the commit. I like it but I also like using the blank green block (or red if root). Perhaps an options should do the job.

**Comment by jeremyFreeAgent** [comment]
ping @mdluo

**Comment by jeremyFreeAgent** [comment]
What do you think?

**Comment by mdluo** [comment]
ok, I'm closing this pr.
Anyone who want to do that as in my description can refer to the changed file.

**Comment by jeremyFreeAgent** [comment]
@mdluo I think on option for that would be great. I will add it.

**Pull request closed without merging**
