### PR TITLE
Fix #41

### LINKED ISSUE #41: Repeat character after tab-complete / expansion
repeat_character

After a tab-complete, a repeat character shows up, and other weird behavior happens at the text prompt.  I've tried suggestions online saying to add the following to the top of my .zshrc:

```
export LC_ALL="en_US.UTF-8"
export LANG="en_US.UTF-8"
export TERM="xterm-256color"
```

Do you have any fixes for this?  I'm on OSX using iTerm2, also using the powerline-fonts.

### PR DESCRIPTION
**Pull request by sumitsahrawat**
This works for me just the way I expect it to. Currently

+ Has no space at the end of RPROMPT.
+ Doesn't duplicate characters at tab-completion.

### CODE REVIEW

**Comment by jeremyFreeAgent** [comment]
Cool!

**Comment by jeremyFreeAgent** [comment]
Thanky @sumitsahrawat

**Comment by jeremyFreeAgent** [comment]
@sumitsahrawat I still have the duplicate at tag completion :(

**Comment by sumitsahrawat** [comment]
I think it differs from system to system. You're right when you say that it'd be best to keep the whitespace at the right :+1:

**Pull request merged**
