### PR TITLE
Added support to virtualenv

### PR DESCRIPTION
**Pull request by lardissone**
Adding the name of the virtualenv at the beginning of the prompt.

Now it looks like the attachment.
prompt

I don't know if it deserves a new color background, probably it does.

### CODE REVIEW

**Comment by jeremyFreeAgent** [comment]
ping @caiogondim

**Comment by caiogondim** [comment]
I'm not the one who made the PR =)

**Comment by jeremyFreeAgent** [comment]
ping @lardissone (lol sorry @caiogondim)

**Comment by wernight** [comment]
I'm now using Powerline additional to OMZ which I think it a superior solution because it offers OMZ alias/completions/scripts but has Powerline "theme" which supports lots of options and dynamic.

**Comment by dtran320** [comment]
Doesn't look like there's been any updates on this PR, so I made the changes off the current upstream master in #54 along with a setting for turning off the virtualenv display. I removed use of the hook, which does mean that if you activate/deactivate the virtualenv, you may need to `source ~/.zshrc` to get things to show correctly again.

**Comment by jeremyFreeAgent** [comment]
See #54

**Pull request closed without merging**
